feat: task array
Mercurical/kouczing pull request #3
Opened 2022-07-10 15:10 UTC by henoth

2022-07-10 18:02 UTC, Mercurical commented on src/tasks/tablica.ts
> +let array: number[]=[1,2,3,4,5];
Nie zmieniamy arraya, więc może być `const`.

2022-07-10 18:04 UTC, Mercurical requested changes

2022-07-10 18:04 UTC, Mercurical commented on src/tasks/tablica.ts
> +    if (array[i] %2 ==0) sum=sum+array[i];
Widzę pójście po najmniejszej linii oporu :D Proponuję wprowadzić wymaganie zastosowania co najmniej jednej z funkcji na tablicy, czyli `Array.filter()` lub `Array.reduce()`.

2022-07-11 09:15 UTC, Mercurical requested changes

2022-07-11 09:15 UTC, Mercurical commented on src/tasks/tablica.ts
> +let sum: number =0;
Cała logika sumowania itp. powinna znaleźć się w funkcji, żeby kod był reużywalny. W tym konkretnym przypadku nie jest.

Mała podpowiedź/informacja: możesz napisać funkcje w funkcji, pamiętaj, że możesz funkcje przypisywać do zmiennych.

2022-07-11 13:19 UTC, henoth commented on src/tasks/tablica.ts
> +let sum: number =0;
Ogólnie to ja zwykłych funkcji nie za bardzo umiem a co dopiero funkcje w funkcji a i tak bez składni z neta tego też bym nie napisał, dlatego zwykle omijam funkcje i pisze tak jak w 1 wersji :P

2022-07-11 16:39 UTC, Mercurical commented on src/tasks/tablica.ts
> +let sum: number =0;
Traktuj funkcję jak taką maszynkę do mielenia mięsa: mięso, które wrzucasz do środka to są argumenty funkcji, natomiast zmielone mięso, które wychodzi, to jest wynik działania tej "maszynki". To, w jaki sposób ta maszynka działa, to implementacja funkcji, czyli kod, który przetwarza argumenty, żeby dać jakiś wynik.

Idąc tą analogią musisz ustalić co u Ciebie będzie mięsem, a co zmielonym mięsem. Podpowiem: wrzucasz do funkcji tablicę początkową, natomiast masz otrzymać na wyjściu zsumowane liczby parzyste. Coś takiego:

```
function sumujParzyste(tablica: number[]) {
    // tutaj będzie kod funkcji, czyli operacje, by osiągnąć wynik
    
    return suma;
}
```

2022-08-09 17:31 UTC, closed without merging